sudo: required
services:
  - docker

script:
  - docker build -t jguarascio/node .
  - docker images jguarascio/node

before_deploy:
  - docker login -u ${docker_username} -p ${docker_password}

deploy:
  provider: script
  script: docker push jguarascio/node
  on:
    branch: master
